services:
  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    mem_limit: 512m
    mem_reservation: 512m
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    command: sh -c "
      /mosquitto/config/create_default_user.sh && \
      mosquitto -c /mosquitto/config/mosquitto.conf"
    volumes:
      - ./mqtt-server/eclipse-mosquitto/config/:/mosquitto/config
      - mosquitto-data:/mosquitto/data
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME:-user}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-user}
    networks:
      - orion-network

  # uart-mqtt-gateway service
  uart-mqtt-gateway:
    build: ./uart-mqtt-gateway
    container_name: uart-mqtt-gateway
    mem_limit: 256m
    mem_reservation: 256m
    user: "root:root"   # A bit dangerous, but needed for serial port access for now
    privileged: true
    restart: unless-stopped
    labels:
      - "autoheal=true"
    volumes:
      - /dev:/dev
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME:-user}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-user}
      - UART_MQTT_GATEWAY_MQTT_BROKER_URL=mqtt5
      - UART_MQTT_GATEWAY_SERIAL_ALLOWED_PORT_NAME_PREFIXES=/dev/ttyUSB,regex:/dev/ttyACM[3-9]
    depends_on:
      - mqtt5
    ports:
      - "8088:8088"
    networks:
      - orion-network

  # rover-controller-service service
  rover-controller-service:
    build: ./rover-controller-service
    container_name: rover-controller-service
    mem_limit: 256m
    mem_reservation: 256m
    restart: unless-stopped
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME:-user}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-user}
      - MQTT_BROKER_URL=mqtt5
    depends_on:
      - mqtt5
    ports:
      - "8880:8880"
    networks:
      - orion-network

  ground-control-web-app:
    build: ./ground-control-web-app
    container_name: ground-control-web-app
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME:-user}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-user}
      - MQTT_BROKER_URL=${IP_ADDRESS_OF_HOST_PC_IN_LOCAL_NETWORK:-mqtt5}
      - MQTT_BROKER_PORT=9001
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    depends_on:
      - mqtt5
    ports:
      - "80:8080"
    networks:
      - orion-network

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=1   # check every 5 seconds
      - AUTOHEAL_START_PERIOD=10
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10   # Docker waits max 10 seconds (the Docker default) for a container to stop before killing during restarts (container overridable via label, see below)
      - DOCKER_SOCK=/var/run/docker.sock   # Unix socket for curl requests to Docker API
      - CURL_TIMEOUT=15     # --max-time seconds for curl requests to Docker API


volumes:
  mosquitto-data:
    driver: local

networks:
  orion-network:
    driver: bridge
